apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: database
  template:
    metadata:
      labels:
        app: database
    spec:
      containers:
      - name: mongo
        image: mongo
        imagePullPolicy: Never
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
          - containerPort: 27017
            name: db-port
        volumeMounts:
          - name: "chess-db"
            mountPath: "/data/db"
      volumes:
        - name: "chess-db"
          persistentVolumeClaim:
            claimName: "db-pvc"
